/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface StarRating {
        "defaultRating": number;
        "numStars": number;
        "rounded": boolean;
    }
}
declare global {
    interface HTMLStarRatingElement extends Components.StarRating, HTMLStencilElement {
    }
    var HTMLStarRatingElement: {
        prototype: HTMLStarRatingElement;
        new (): HTMLStarRatingElement;
    };
    interface HTMLElementTagNameMap {
        "star-rating": HTMLStarRatingElement;
    }
}
declare namespace LocalJSX {
    interface StarRating {
        "defaultRating"?: number;
        "numStars"?: number;
        "onRatingChange"?: (event: CustomEvent<any>) => void;
        "rounded"?: boolean;
    }
    interface IntrinsicElements {
        "star-rating": StarRating;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "star-rating": LocalJSX.StarRating & JSXBase.HTMLAttributes<HTMLStarRatingElement>;
        }
    }
}
